# https://taskfile.dev/

version: '3'

tasks:
  default:
    cmds:
      - NXF_VER=21.04.0 nextflow run main.nf -params-file params/params.yml -resume -with-tower

  with_stubs:
    cmds:
      - NXF_VER=21.04.0 nextflow run main.nf -params-file params/stub_params.yml -resume -stub -with-tower
